name: CI
on:
  push:
  pull_request:
env:
  BuildDocEnabled: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
  CMakeVersion: 3.14.x
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        vulkan-version: [1.3.224.1]
        build-shared: [ON, OFF]
        vsg-tag: [master, VulkanSceneGraph-1.0]
          
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: ${{ env.CMakeVersion }}

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: ${{ matrix.vulkan-version }}
        cache: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      if: startsWith(matrix.os, 'windows')

    - name: Checkout vsg
      uses: actions/checkout@v2
      ref: ${{matrix.vsg-tag}}

    - name: Build and Install VSG
      shell: bash
      run: |
        cmake . -DBUILD_SHARED_LIBS=${{matrix.build-shared}} -DCMAKE_INSTALL_PREFIX=./install
        cmake --build . --target install --config Release

    - name: Build and Install VSGVR
      shell: bash
      run: |
        cmake . -DBUILD_SHARED_LIBS=${{matrix.build-shared}} -DCMAKE_INSTALL_PREFIX=./install
        cmake --build . --target install --config Release
